name       : mdadm
version    : 4.1
release    : 3
source     :
    - https://www.kernel.org/pub/linux/utils/raid/mdadm/mdadm-4.1.tar.xz : ab7688842908d3583a704d491956f31324c3a5fc9f6a04653cb75d19f1934f4a
license    : GPL-2.0-only
component  : system.utils
summary    : MDADM - Software Raid Management
description: |
    A tool for managing/monitoring Linux md device arrays, also known as Software RAID
build      : |
    %make CXFLAGS="$CFLAGS"
install    : |
    %make_install
