name       : mdadm
version    : 3.3.4
release    : 1
source     :
    - https://www.kernel.org/pub/linux/utils/raid/mdadm/mdadm-3.3.4.tar.xz : 8ae5f45306b873190e91f410709b00e51997b633c072b33f8efd9f7df022ca68
license    : GPL-2.0
summary    : MDADM - Software Raid Management
description: |
    A tool for managing/monitoring Linux md device arrays, also known as Software RAID
build      : |
    %make
install    : |
    %make_install
