name       : mdadm
version    : 4.0
release    : 2
source     :
    - https://www.kernel.org/pub/linux/utils/raid/mdadm/mdadm-4.0.tar.xz : 1d6ae7f24ced3a0fa7b5613b32f4a589bb4881e3946a5a2c3724056254ada3a9
license    : GPL-2.0-only
component  : system.utils
summary    : MDADM - Software Raid Management
description: |
    A tool for managing/monitoring Linux md device arrays, also known as Software RAID
build      : |
    %make CXFLAGS="$CFLAGS"
install    : |
    %make_install
